### ISSUE TITLE
implement github workflow to run on multiple platforms

### ISSUE THREAD

**Issue by uncojohnco** [uncojohnco/test-jc--dd-2019#27]
https://github.com/ymyzk/tox-gh-actions
https://hynek.me/articles/python-github-actions/

tests-doctest-module.yml - WIP
```
name: Doctest

on:
  push:
    paths:
      - 'src/lss/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Run Doctests (temp - ignore )
      run: |
        pytest src/lss --doctest-modules --ignore=notebooks  --ignore=src/lss/lsseq.py
      env:
        PLATFORM: ${{ matrix.platform }}

```
